### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/latest_model.txt'

### ISSUE THREAD

**Issue by laxmimerit** [o19s/hello-ltr#42] opened 2020-07-12 08:39 UTC
Hi,
I am trying to run it on Ubuntu 18.04 as described in the readme file. When I run this code in `hello-ltr[ES]`

```
from ltr.ranklib import train
train(client, training_set=latest_training_set, 
      index='tmdb', featureSet='release', modelName='latest')
train(client, training_set=classic_training_set, 
      index='tmdb', featureSet='release', modelName='classic')
```

I am getting this error

```
/tmp/RankyMcRankFace.jar already exists
Running java -jar /tmp/RankyMcRankFace.jar -ranker 6 -shrinkage 0.1 -metric2t DCG@10 -tree 50 -bag 1 -leaf 10 -frate 1.0 -srate 1.0 -train /tmp/training.txt -save data/latest_model.txt 
DONE

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-8-61d89782267a> in <module>
      1 from ltr.ranklib import train
      2 train(client, training_set=latest_training_set, 
----> 3       index='tmdb', featureSet='release', modelName='latest')
      4 train(client, training_set=classic_training_set, 
      5       index='tmdb', featureSet='release', modelName='classic')

~/Documents/hello-ltr/ltr/ranklib.py in train(client, training_set, modelName, featureSet, index, features, metric2t, leafs, trees, frate, srate, bag, ranker, shrinkage)
     80                                trees=trees,
     81                                shrinkage=shrinkage)
---> 82     save_model(client, modelName, modelFile, index, featureSet)
     83     assert len(ranklibResult.trainingLogs) == 1
     84     return ranklibResult.trainingLogs[0]

~/Documents/hello-ltr/ltr/ranklib.py in save_model(client, modelName, modelFile, index, featureSet)
     56 
     57 def save_model(client, modelName, modelFile, index, featureSet):
---> 58     with open(modelFile) as src:
     59         definition = src.read()
     60         client.submit_ranklib_model(featureSet, index, modelName, definition)

FileNotFoundError: [Errno 2] No such file or directory: 'data/latest_model.txt'

```

Any suggestion to avoid this error?

**Comment by laxmimerit** [comment] 2020-07-13 08:18
Update 1:
Sometimes it works and sometimes it does not. For instance, I got it working some time ago and then again after a restart of computer it is showing same error. 
Any suggestion?

**Comment by laxmimerit** [comment] 2020-07-13 11:54
Update 2:
It seems this command is not writing a model on disk.
```
    print("Running %s" % cmd)
    result = os.popen(cmd).read()
    print("DONE")
    return parse_training_log(result)
```
I get this

```
Running java -jar /tmp/RankyMcRankFace.jar -ranker 6 -shrinkage 0.1 -metric2t DCG@10 -tree 50 -bag 1 -leaf 10 -frate 1.0 -srate 1.0 -train /tmp/training.txt -save /home/laxmi/Documents/hello-ltr/notebooks/elasticsearch/tmdb/data/title_model.txt 
```
I wasn't able to run it with the default path so tried to use an absolute path. So in ranklib.train(), I did this

```
modelFile='/home/laxmi/Documents/hello-ltr/notebooks/elasticsearch/tmdb/data/{}_model.txt'.format(modelName)

```


I should see `title_model.txt` in the `data` folder but it is not there. 

Does it mean that the trained model is not being stored?

**Comment by laxmimerit** [comment] 2020-07-13 16:49
**Update 3**
This is really very strange. I have been scratching my head. Same config, same code and now it has started working. 
<img width="750" alt="es-basic-part1" src="https://user-images.githubusercontent.com/16714612/87330573-69bbdc00-c556-11ea-9034-4d665fbbb145.png">

Not sure for how much time it is gonna work. As I have already pointed in Update 1, sometimes it works and sometimes it doesn't. I have added a few print statements in `ranklib.py`. 
Any suggestions to debug the real problems?

**Comment by nathancday** [comment] 2020-10-19 21:18
Hi @laxmimerit,

1) Sorry it took so long to respond.
2) It looks like a situation were you are trying to work outside of the docker machine while still using the docker paths. 

Since this is difficult to reproduce outside of the docker context I'm closing for now, if this persists please re-open.

**Closed as completed by nathancday** 2020-10-19 21:18 UTC
